<a href="https://colab.research.google.com/github/ShresthaPriya/AI-and-ML/blob/main/Worksheet0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise on Functions:

**Task - 1:**

In [ ]:
def convert_MeasurementUnits(value, From, To):
    """
    Converts a value from one unit to another.

    This function takes three arguments where:
        value (float): The value to be converted.
        from_unit (str): The original measurement unit to convert.
        to_unit (str): The measurement unit to be converted into.
and perform conversion operation and Returns the converted value on success, if the conversion is not supported, return none.

    """

    if From == "m" and To == "ft":
        return value * 3.28084
    elif From == "ft" and To == "m":
        return value / 3.28084
    elif From == "kg" and To == "lbs":
        return value * 2.20462
    elif From == "lbs" and To == "kg":
        return value / 2.20462
    elif From == "L" and To == "gal":
        return value * 0.264172
    elif From == "gal" and To == "L":
        return value / 0.264172
    else:
        return None

def main():
    """
    This function prompts the user input to choose the type of conversion as well as the unit to convert and unit to converted into and the value to convert, then call the
    user-defined function to perform the conversion
    """
    print("Choose conversion type:")
    print("1. Length (m <-> ft)")
    print("2. Weight (kg <-> lbs)")
    print("3. Volume (L <-> gal)")

    while True:
        try:
            choice = int(input("Enter your choice (1/2/3): "))
            if choice in [1, 2, 3]:
                break
            else:
                print("Invalid choice. Please enter 1, 2, or 3.")
        except ValueError:
            print("Invalid input. Please enter a number.")

    if choice == 1:
        From = input("Enter original unit to convert(m/ft): ").lower()
        To = input("Enter target unit (m/ft) to convert into: ").lower()
    elif choice == 2:
        From = input("Enter original unit to convert(kg/lbs): ").lower()
        To = input("Enter target unit (kg/lbs) to convert into: ").lower()
    else:
        From = input("Enter original unit to convert(L/gal): ").lower()
        To = input("Enter target unit (L/gal) to convert into: ").lower()

    while True:
        try:
            value = float(input("Enter value to convert: "))
            break
        except ValueError:
            print("Invalid input. Please enter a number.")

    result = convert_MeasurementUnits(value, From, To)

    if result is not None:
        print(f"{value} {From} is equal to {result:.2f} {To}")
    else:
        print("Conversion not supported.")

if __name__ == "__main__":
    main()

Choose conversion type:
1. Length (m <-> ft)
2. Weight (kg <-> lbs)
3. Volume (L <-> gal)
Enter your choice (1/2/3): 1
Enter original unit to convert(m/ft): m
Enter target unit (m/ft) to convert into: ft
Enter value to convert: 150
150.0 m is equal to 492.13 ft


# Task - 2:
**Create a Python program that performs various mathematical operations on a list of numbers.**

In [ ]:
def calculate_sum(numbers):
  """Calculates and returns sum of numbers in the list using for loop.
     Takes parameter (numbers)
  """
  try:
    total = 0
    for i in numbers:
      total+= i
    return total
  except TypeError:
    return None

def calculate_average(numbers):
  """This function takes numbers as parameter, calculates and returns average of numbers in the list using for loop"""
  try:
    total = 0
    count =0
    for i in numbers:
      total ++ i
      count += 1
      average = total /count
    return average if count > 0 else 0
  except (TypeError, ZeroDivisionError):
    return None

def find_max(numbers):
  """Takes numbers as parameter, finds and returns maximum number in the list using for loop"""
  max_val = numbers[0]
  for i in numbers:
      if i > max_val:
          max_val = i
  return max_val



def find_min(numbers):
  """Finds and returns minimum number in the list"""
  try:
    return min(numbers)
  except TypeError:
    return None

def main():
  """
  This functions prompts user input to choose the operation from 1-4 to perform and numbers in the list
  separated by space and has the necessary error handling for invalid inputs and call the specific
  function upon choosing the numbers to perform the selected operation, the main function executes the program.


  """
  print("Choose the operation to perform")
  print("1. Sum")
  print("2. Average")
  print("3. Maximum")
  print("4. Minimum")
  while True:
    try:
      choice = int(input("Enter your choice (1-4): "))
      if 1 <= choice <= 4:
        break
      else:
        print("Invalid choice. Enter the number from 1 - 4")
    except ValueError:
      print("Invalid input. Please enter a number only.")

  while True:
    try:
       numbers = list(map(float, input("Enter a list of numbers separated by spaces: ").split()))
       if not numbers:
        raise ValueError("List cannot be empty.")
       break
    except ValueError:
      print("Invalid input. Enter the number separated by spaces")

  if choice == 1:
      result = calculate_sum(numbers)
      operation = "Sum"
  elif choice == 2:
      result = calculate_average(numbers)
      operation = "Average"
  elif choice == 3:
      result =find_max(numbers)
      operation = "Maximum"
  elif choice == 4:
      result = find_min(numbers)
      operation = "Minimum"
  else:
      print("Invalid choice")
      return

  print(f"The {operation} of numbers is: {result:.2f}")



if __name__ == "__main__":
    main()



Choose the operation to perform
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice (1-4): 3
Enter a list of numbers separated by spaces: 2 4 6 8 10
The Maximum of numbers is: 10.00


# 4.2 Exercise on List Manipulation:




1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element. **bold text**

In [7]:
def extract_every_other(lst):
  """
  This function uses slicing to extracts every other elements from the list starting from first element.  """
  return lst [::2]
lists = [1,2,3,4,5]
newList = extract_every_other(lists)
print(f"1. The new list after extracts every other elements from the list is {newList}.")

1. The new list after extracts every other elements from the list is [1, 3, 5].


**2. Slice a Sublist:**
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

In [ ]:
def get_sublist(lst, start, end):
  """This function returns sublist from the list based on specified start and end index."""
  return lst [start:end +1]
lists = [1,2,3,4,5]
start_idx = 2
end_idx = 4
newList = get_sublist(lists, start_idx, end_idx)
print(f"The new list is {newList}")

The new list is [3, 4, 5]


**3. Reverse a List Using Slicing:**
Write a Python function that reverses a list using slicing

– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [ ]:
def reverse_list(lst):
  """This function gives the reversed list of the given list using slicing"""
  return lst[::-1]

lists = [1,2,3,4,5]
newList = reverse_list(lists)
print(f"New list after reverse is {newList}")

New list after reverse is [5, 4, 3, 2, 1]


**4. Remove the First and Last Elements:**
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.


In [ ]:
def remove_first_last(lst):
  """ This function removes the first and last elements of the list and make a new list  """
  return lst[1:-1]
my_lst = [1,2,3,4,5]
newList = remove_first_last(my_lst)
print(f"The new list after removing first and last elements: {newList}")

The new list after removing first and last elements: [2, 3, 4]


5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.

In [ ]:
def get_first_n(lst, n):
  """ This function extracts the first n elements of a list using slicing """
  return lst[:n]
my_lst = [1,2,3,4,5]
n = 3
newList = get_first_n(my_lst, n)
print(f"The new list containing first n elements of the list: {newList}")

The new list containing first n elements of the list: [1, 2, 3]


6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.

In [ ]:
def get_last_n(lst, n):
  """ This function extracts the last n elements of a list using slicing """
  return lst[-n:]
my_lst = [1,2,3,4,5]
n = 2
newList = get_last_n(my_lst, n)
print(f"The new list containing last n elements of the list: {newList}")

The new list containing last n elements of the list: [4, 5]


7. Extract Elements in Reverse Order:

In [ ]:
def reverse_skip(lst):
  """ This function extracts the elements of a list in reverse order skipping one element in between using slicing """
  return lst[-2::-2]
my_lst = [1,2,3,4,5,6]
reversedList = reverse_skip(my_lst)
print(f"The reversed list starting from second to last: {reversedList}")

The reversed list starting from second to last: [5, 3, 1]


# 4.3 Exercise on Nested List:

**1. Flatten a Nested List:**
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

In [ ]:
def flatten(lst):
    """This function   takes a nested list "lst" and flatten it into single array usibg nestes for loop"""
    flattenList = []
    # Iterate with outer list
    for element in lst:
        if type(element) is list:
            # irrate overeach element and append to the list
            for item in element:
                flattenList.append(item)
        else:
            flattenList.append(element)
    return flattenList
my_list =[[1, 2], [3, 4], [5]]
print('Original List:', my_list)
print('Flat List:', flatten(my_list))

Original List: [[1, 2], [3, 4], [5]]
Flat List: [1, 2, 3, 4, 5]


**2. Accessing Nested List Elements:**
Write a Python function that extracts a specific element from a nested list given its indices.


– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.

– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [ ]:
def access_nested_element(lst, indices):
  """This function extracts a specific element from a nested list unsing the given indices."""
  try:
        element = lst
        for index in indices:
            element = element[index]
        return element
  except (IndexError, TypeError):
      return None


lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
result = access_nested_element(lst, indices)
print(f"The element in {indices} of the nested list {lst} is {result}")

The element in [1, 2] of the nested list [[1, 2, 3], [4, 5, 6], [7, 8, 9]] is 6


**3. Sum of All Elements in a Nested List:**

* Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).


* Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.

In [ ]:
def sum_nested(lst):
   """ This function sums all the elements in the nested list recursively """
   try:
    total = 0
    for i in range(len(lst)):
      if type(lst[i]) == list:

        total += sum_nested(lst[i])
      else:
        total += lst[i]
    return total
   except (IndexError, TypeError):
    return None

lst = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(lst)
print(f"The sum of all elements in given list is: {result}")

The sum of all elements in given list is: 21


**4. Remove Specific Element from a Nested List:**

In [ ]:
def remove_element(lst, elem):
  """ This function takes two arguments a list and element to remove "elem" and removes the specific element from the list recursively """
  try:
    result = []
    for i in range(len(lst)):
      if type(lst[i]) == list: # check if the element is a list
        modified_lst = remove_element(lst[i], elem)
        if modified_lst: #if non empty
          result.append(modified_lst)
      elif lst[i] != elem:
        result.append(lst[i]) #keep elements except for the elem
    return result
  except (IndexError, TypeError):
    return lst

lst = [[1, 2], [3, 2], [4, 5]]
elem = 2
result = remove_element(lst, elem)
print(f"The modified list after removing {elem} is {result}")

The modified list after removing 2 is [[1], [3], [4, 5]]


**5. Find the Maximum Element in a Nested List:**

In [ ]:
def find_max(lst):
  """ This function takes  argument list (lst)  and finds the max element from the nested list recursively """
  try:
    max_val = float('-inf')
    for i in range(len(lst)):
      if type(lst[i]) == list: # check if the element is a list
        max_val = max(max_val,find_max(lst[i]))
      else:
        max_val = max(max_val,lst[i])
    return max_val
  except  TypeError:
    return lst

lst = [[1, 2], [3, 12], [4, 5]]
result = find_max(lst)
print(f"The maximum element in the list is {result}")

The maximum element in the list is 12


**6. Count Occurrences of an Element in a Nested List:**

In [ ]:
def count_occurrence(lst, elem):
  """ This function takes two arguments a list and element to remove "elem" and counts the no.of repeatition of given element in the list"""

  count = 0
  for i in range(len(lst)):
    if isinstance(lst[i], list): # check if the element is a list
      count += count_occurrence(lst[i], elem)
    elif lst[i] == elem:
      count += 1 #increase the count
  return count
lst = [[1, 2], [3, 2], [2,4]]
elem = 2
result = count_occurrence(lst, elem)
print(f"The element {elem} has appeared {result} times in the list")

The element 2 has appeared 3 times in the list


**7. Flatten a List of Lists of Lists:**

In [ ]:
def deep_flatten(lst):
  """This function flattens the nested list into a single list"""
  flat=[]
  for item in lst:
    if isinstance(item,list):
      flat.extend(deep_flatten(item))
    else:
      flat.append(item)
  return flat

lst = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(lst)
print(f"The flattened list is {result}")

The flattened list is [1, 2, 3, 4, 5, 6, 7, 8]


**8. Nested List Average:**

* Write a Python function that calculates the average of all elements in a nested list.

In [ ]:
def average_nested(lst):
    """This function recursively calculates the average of all elements in a nested list."""
    def deep_flatten(lst):
        """This function flattens the nested list into a single list"""
        flattened = []
        for item in lst:
            if isinstance(item, list):
                flattened.extend(deep_flatten(item))
            else:
                flattened.append(item)  # Add non-list elements
        return flattened
    flat_list = deep_flatten(lst)  # extract a single list of all numbers
    if not flat_list:
        return 0.0
    return sum(flat_list) / len(flat_list)  # Compute average
lst = [[1, 2], [3, 4], [5, 6]]
result = average_nested(lst)
print(f"The average of all elements is {result}")

The average of all elements is 3.5


# To - Do - NumPy


# Basic Vector and Matrix Operation with Numpy.
**Problem - 1: Array Creation:**


In [ ]:
import numpy as np

In [9]:
#initialise empty array with 2 * 2
arr = np.zeros((2,2))
print("1.Initialise empty array with 2 * 2\n")
print(arr)

#Initialize an all one array with size 4X2.
arr = np.ones((4,2))
print("\n2.Initialize an all one array with size 4X2.\n")
print(arr)

#3. Return a new array of given shape and type, filled with fill_value. {Hint: np.full}
arr = np.full((4,2), 7, dtype=int)
print("\n3. Return a new array of given shape and type, filled with fill_value.\n")
print(arr)

#4. Return a new array of zeros with same shape and type as a given array. {Hint: np.zeros_like}
arr = np.full((4,2), 7, dtype=int)
new_arr= np.zeros_like(arr)
print("\n4. Return a new array of zeros with same shape and type as a given array.\n")
print(f"Given array:\n {arr}\n")
print(f"New array:\n {new_arr}")

#5. Return a new array of ones with same shape and type as a given array. {Hint: np.ones_like}
arr = np.array([[2,1,3], [3,4,7]])
new_arr = np.ones_like(arr)
print("\n5. Return a new array of ones with same shape and type as a given array.\n")
print(f"Given array:\n {arr}\n")
print(f"New array:\n {new_arr}")

#6. For an existing list new_list = [1,2,3,4] convert to a numpy array. {Hint: np.array()}
new_list = [1,2,3,4]
new_arr = np.array(new_list)
print("\n6. For an existing list new_list = [1,2,3,4] convert to a numpy array.\n")
print(f"The list {new_list} is converted into array {new_arr}")
print(type(new_arr))

1.Initialise empty array with 2 * 2

[[0. 0.]
 [0. 0.]]

2.Initialize an all one array with size 4X2.

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Return a new array of given shape and type, filled with fill_value.

[[7 7]
 [7 7]
 [7 7]
 [7 7]]

4. Return a new array of zeros with same shape and type as a given array.

Given array:
 [[7 7]
 [7 7]
 [7 7]
 [7 7]]

New array:
 [[0 0]
 [0 0]
 [0 0]
 [0 0]]

5. Return a new array of ones with same shape and type as a given array.

Given array:
 [[2 1 3]
 [3 4 7]]

New array:
 [[1 1 1]
 [1 1 1]]

6. For an existing list new_list = [1,2,3,4] convert to a numpy array.

The list [1, 2, 3, 4] is converted into array [1 2 3 4]
<class 'numpy.ndarray'>


# Problem - 2: Array Manipulation: Numerical Ranges and Array Indexing

In [6]:
#Create an array with values ranging from 10 to 49.{Hint: np.arange()}
arr = np.arange(10, 50)
print(f"An array with values ranging from 10 to 49:\n {arr}")

An array with values ranging from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#Create a 3×3 matrix with values ranging from 0 to 8. {Hint: look for np.reshape()}
arr = np.arange(9).reshape(3, 3)
print(f"3×3 matrix with values ranging from 0 to 8:\n {arr}")

3×3 matrix with values ranging from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#Create a 3×3 identity matrix. {Hint: np.eye()}
arr = np.eye(3,3)
print(f"The 3×3 identity matrix: \n {arr}")

The 3×3 identity matrix: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Create a random array of size 30 and find the mean of the array.{Hint: check for np.random.random() and array.mean() function}
from numpy import random
arr = np.random.random(30)
arr1 = arr.mean()
print(f"The mean of the array:\n {arr1}")

The mean of the array:
 0.5380685160827771


In [ ]:
#Create a 10×10 array with random values and find the minimum and maximum values.
arr = np.random.rand(10,10)
max_val= np.max(arr)
min_val= np.min(arr)
print(f"The min and max values are: ({max_val}, {min_val})")

The min and max values are: (0.9920140749327123, 0.0056073958650968425)


In [5]:
#Create a zero array of size 10 and replace the 5th element with 1.
arr = np.zeros(10)
arr[4]=1
print(f"Zero array of size 10 and replace the 5th element with 1: ",arr)

Zero array of size 10 and replace the 5th element with 1:  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#Reverse an array arr = [1,2,0,0,4,0].
arr = [1,2,0,0,4,0]
rev_arr = arr[::-1]
print(f"The original array is: {arr}\n The reversed array is: {rev_arr}")

The original array is: [1, 2, 0, 0, 4, 0]
 The reversed array is: [0, 4, 0, 0, 2, 1]


In [ ]:
#Create a 2D array with 1 on the border and 0 inside.
#create a 2/2 matrix with ones
arr= np.ones((5,5))
##fill inside with 0
arr[1:-1,1:-1]=0
print(f"2D array with 1 on the border and 0 inside:\n {arr}")

2D array with 1 on the border and 0 inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Creating a 3x3 NumPy array filled with ones
arr = np.ones((3, 3))

# Creating an 8x8 zero matrix
arr= np.zeros((8, 8), dtype=int)
arr[1::2, ::2] = 1
arr[::2, 1::2] = 1

# Printing the resulting checkerboard pattern array
print(f"Checkerboard pattern:\n {arr}")

Checkerboard pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**Problem - 3: Array Operations:**

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);

In [ ]:
#add two arrays
print("Q1.Add two array")
x = np.array([[1,2],[3,5]])
y=np.array([[5,6],[7,8]])
addXY= x+y #perform add
print(f"Adding X and Y:\n {addXY}\n")
v = np.array([9,10])
w = np.array([11,12])
addVW = v+w #perform add
print(f"Adding V and W:\n {addVW}\n")

print("Q2.Substract two array")
x = np.array([[1,2],[3,5]])
y=np.array([[5,6],[7,8]])
subXY= x-y #perform substract
print(f"Substracting X and Y:\n {subXY}\n")
v = np.array([9,10])
w = np.array([11,12])
subVW = v-w #perform substract
print(f"Substracting V and W:\n {subVW}\n")

Q1.Add two array
Adding X and Y:
 [[ 6  8]
 [10 13]]

Adding V and W:
 [20 22]

Q2.Substract two array
Substracting X and Y:
 [[-4 -4]
 [-4 -3]]

Substracting V and W:
 [-2 -2]



In [ ]:
print("Q3. Multiply the array with an integer (5)")
x = np.array([[1,2],[3,5]])
y=np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
#perform multiply with integer 5
mulx= x*5
muly= y*5
mulv = v*5
mulw = w*5
#print result of multiplication of array with integer 5
print(f"Multiplication X with 5:\n {mulx}\n")
print(f"Multiplication Y with 5:\n {muly}\n")
print(f"Multiplication V with 5:\n {mulv}\n")
print(f"Multiplication W with 5:\n {mulw}\n")

Q3. Multiply the array with an integer (5)
Multiplication X with 5:
 [[ 5 10]
 [15 25]]

Multiplication Y with 5:
 [[25 30]
 [35 40]]

Multiplication V with 5:
 [45 50]

Multiplication W with 5:
 [55 60]



In [ ]:
print("Q.4. Find the square of each element of the array")
x = np.array([[1,2],[3,5]])
y=np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
sqX= x**2 #perform square of each element of array
sqY= y**2
sqV = v**2
sqW = w**2
#print the of each element of the array
print(f"Sqaure of each element of the arrayX:\n {sqX}\n")
print(f"Sqaure of each element of the arrayY:\n {sqY}\n")
print(f"Sqaure of each element of the arrayV:\n {sqV}\n")
print(f"Sqaure of each element of the arrayW:\n {sqW}\n")


Q.4. Find the square of each element of the array
Sqaure of each element of the arrayX:
 [[ 1  4]
 [ 9 25]]

Sqaure of each element of the arrayY:
 [[25 36]
 [49 64]]

Sqaure of each element of the arrayV:
 [ 81 100]

Sqaure of each element of the arrayW:
 [121 144]



In [ ]:
import numpy as np

print("Q.5. Find the dot product\n")
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
#dot product of the given array
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
#displau result of dot product
print("Dot product v·w:", dot_vw)
print("Dot product x·v:\n", dot_xv)
print("Dot product x·y:\n", dot_xy)

Q.5. Find the dot product

Dot product v·w: 219
Dot product x·v:
 [29 77]
Dot product x·y:
 [[19 22]
 [50 58]]


In [ ]:
#Concatenate x(and)y along row and Concatenate v(and)w along column.
# {Hint:try np.concatenate() or np.vstack() functions.
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

xy_concate = np.concatenate((x,y), axis=0)

#reshape v and w into col vectors

vCol = v.reshape(-1, 1)
wCol = w.reshape(-1, 1)

#concatenate v and w along column
vw_concate = np.concatenate((vCol,wCol), axis=1)

#display the results
print(f"Concatenate x(and)y along row:\n {xy_concate}\n")
print(f"Concatenate v(and)w along col:\n {vw_concate}\n")

Concatenate x(and)y along row:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v(and)w along col:
 [[ 9 11]
 [10 12]]



In [ ]:
#Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
x = np.array([[1,2],[3,5]])
v = np.array([9,10])
xv_concate = np.concatenate((x,v), axis=0)
print(xv_concate)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

**Answer**

* ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
We get this value error while concatenating x and v as X  is 2D array having dimension 2x2 but v is 1D array. Hence, the error is occuring. For concatenation to work, v also should have same no.of column as x i.e 2. Hence, v needs to be reshaped to be able to perform concatenation with x.

# Problem - 4: Matrix Operations:

• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT

In [4]:
#prove A.A−1 = I.
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# Compute the inverse of A
A_inverse = np.linalg.inv(A)

# Compute A * A_inv
I = np.dot(A, A_inverse)
I_expected = np.eye(2)

print("1.prove A.A−1 = I.\n")
# Print results
print("A * A⁻¹ = \n", I)
print("\nIdentity matrix:\n ",I_expected)
print("Is A * A⁻¹ approximately equal to Identity Matrix?:", np.allclose(I, I_expected))

#Prove AB ̸= BA.
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

AB = np.dot(A,B)
BA = np.dot(B,A)
print("\n2. Prove AB ̸= BA.\n")
print("AB:\n" ,AB)
print("BA:\n", BA)
if not np.array_equal(AB, BA):
  print("AB  ̸= BA")

# 3. Prove (AB)ᵀ = Bᵀ * Aᵀ
AB_T= np.transpose(AB)
BT_AT = np.dot(B.T, A.T)
print("\n3. Prove (AB)ᵀ = Bᵀ * Aᵀ")
print("\n(AB)ᵀ:\n", AB_T)
print("\nBᵀ * Aᵀ:\n", BT_AT)
if np.array_equal(AB_T, BT_AT):
    print("\n(AB)ᵀ = Bᵀ * Aᵀ")

1.prove A.A−1 = I.

A * A⁻¹ = 
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Identity matrix:
  [[1. 0.]
 [0. 1.]]
Is A * A⁻¹ approximately equal to Identity Matrix?: True

2. Prove AB ̸= BA.

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB  ̸= BA

3. Prove (AB)ᵀ = Bᵀ * Aᵀ

(AB)ᵀ:
 [[23 51]
 [13 29]]

Bᵀ * Aᵀ:
 [[23 51]
 [13 29]]

(AB)ᵀ = Bᵀ * Aᵀ


# 4. Solve Linear Equations using Inverse Methods
# System of equations:
#  2x - 3y + z = -1
#  x - y + 2z = -3
#  3x + y - z = 9



In [ ]:
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B= np.array([-1, -3, 9])

A_inv = np.linalg.inv(A) #inverse of A
result = np.dot(A_inv, B) #dot product of A inverse and B
print("\nThe value of x,y,x after solving the Linear Equations (x, y, z):\n", result)


The value of x,y,x after solving the Linear Equations (x, y, z):
 [ 2.  1. -2.]


# How fast is numpy


In [2]:
import numpy as np
import time

size = 1_000_000
matrix_size = 1000

# Generate random data
listA = [i for i in range(size)]
listB = [i for i in range(size)]

arr1 = np.arange(size)
arr2 = np.arange(size)

# 1. Element-wise Addition
# Using Python Lists
print("1. Element-wise Addition\n")
start_time = time.time()
list_addition = [listA[i] + listB[i] for i in range(size)]
addition_time = time.time() - start_time
print(f"Time taken to perform element-wise addition of two lists: {addition_time:.5f} seconds")

#Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
# this operation.
start_time = time.time()
numpy_add= arr1 + arr2
time_numpy_add = time.time() - start_time
print(f"Time taken for numpy array addition: {time_numpy_add:.5f} seconds")

# 2. Element-wise Multiplication
# Using Python Lists, perform element-wise multiplication of two lists of size
print("\n 2. Element-wise Multiplication\n")
start_time = time.time()
list_mul = [listA[i] * listB[i] for i in range(size)]
mul_time = time.time() - start_time
print(f"\nTime take to perform element-wise multiplication of two lists of size: {mul_time:.5f} seconds")

# Using Numpy Arrays, Repeat the calculation and measure and print the time taken
start_time = time.time()
numpy_mul = arr1 * arr2
numpy_mul_time = time.time() - start_time
print(f"Time taken for numpy array multiplication:  {numpy_mul_time:.5f} seconds")

# 3. Dot Product
# Using Python Lists, compute the dot product of two lists of size
print("\n 3. Dot Product\n")
start_time = time.time()
dot_prod = sum(listA[i] * listB[i] for i in range(size))
dot_prod_time = time.time() - start_time
print(f"\nTime taken to compute the dot product of two lists of size: {dot_prod_time:.5f} seconds")

# Using NumPy Arrays
start_time = time.time()
numpy_dot_prod = np.dot(arr1, arr2)
numpy_dot_prod_time = time.time() - start_time
print(f"Time taken for NumPy Arrays Dot Product: {numpy_dot_prod_time:.5f} seconds")

# 4. Matrix Multiplication
# Generate random matrices
print("\n 4. Matrix Multiplication\n")
list_mat1 = [[j for j in range(matrix_size)] for i in range(matrix_size)]
list_mat2 = [[j for j in range(matrix_size)] for i in range(matrix_size)]

numpy_mat1 = np.arange(matrix_size ** 2).reshape(matrix_size, matrix_size)
numpy_mat2 = np.arange(matrix_size ** 2).reshape(matrix_size, matrix_size)

# Using Python Lists
start_time = time.time()
resultant_matrix = [[sum(a * b for a, b in zip(row, col)) for col in zip(*list_mat2)] for row in list_mat1]
matrix_multiplication_time = time.time() - start_time
print(f"\nTime taken to perform matrix multiplication of two matrices: {matrix_multiplication_time:.5f} seconds")

# Using NumPy Arrays
start_time = time.time()
numpy_mat_multiplication = np.dot(numpy_mat1, numpy_mat2)
numpy_mat_multiplication_time = time.time() - start_time
print(f"Time taken NumPy Arrays Matrix Multiplication: {numpy_mat_multiplication_time:.5f} seconds")

1. Element-wise Addition

Time taken to perform element-wise addition of two lists: 0.13647 seconds
Time taken for numpy array addition: 0.00597 seconds

 2. Element-wise Multiplication


Time take to perform element-wise multiplication of two lists of size: 0.20069 seconds
Time taken for numpy array multiplication:  0.00490 seconds

 3. Dot Product


Time taken to compute the dot product of two lists of size: 0.21261 seconds
Time taken for NumPy Arrays Dot Product: 0.00257 seconds

 4. Matrix Multiplication


Time taken to perform matrix multiplication of two matrices: 166.97600 seconds
Time taken NumPy Arrays Matrix Multiplication: 1.24529 seconds
